# Site settings
name: 從此迷花粉
email: 528050239@qq.com
author: cherrishccl
url: https://cherrishccl.github.io
resume_site: https://cherrishccl.github.io
github: https://github.com/cherrishccl
baseurl: "/"
description: Actually, less is more!
meta_description: WHO AM I;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: You still have lots more to work on.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cherrishccl

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

